---
functional:
  - пользователь имеет возможность создать игру против бота, друга или любого человека
  - пользователь имеет возможность выбрать уровень сложности при создании игры
  - пользователь при создании игры имеет возможность выбрать лимит времени игры
  - при создании игры пользователь имеет возможность выбрать задачу
  - пользователь имеет возможность наблюдать за игрой других игроков в режиме реального времени
  - Каждый игрок видит код своего соперника в режиме он-лайн
  - пользователь имеет возможность просматривать завершенные игры в записи
  - задача в игровом режиме может отображаться на двух языках - русском и английском
  - в игре есть чат, в котором могут общаться зарегистрированные пользователи
  - за решение задач пользователи получают очки, на основе которых формируется рейтинг игроков за неделю, месяц и за все время
  - пользователь имеет возможность участвовать в турнирах
  - игрок может проверить правильность своего решения по нажатию на кнопку
  - при правильном решении игрок-побкдитель видит модальное окно с информацией о его победе
  - игрок может завершить игру в любой момент
  - на главной странице отображаются три вкладки: LOBBY, TOURNAMENTS, COMPLETED GAMES
  - во вкладке LOBBY отображаются текущие игры
  - во вкладке TOURNAMENTS отображаются активные и завершенные турниры
  - во вкладке COMPLETED GAMES отображаются все завершенные игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
