---
functional:
  - пользователь должен иметь возможность зарегистрироваться на сайте как с помощью электронного адреса, так и с помощью учетной записи на Github или Discord
  - форма регистрации должна содержать следующие поля ввода "имя пользователя", "адрес электронной почты", "пароль", "подтверждение пароля"
  - регистрация пользователя не должна осуществляться при хотябы одном незаполненном поле
  - имя пользователя при регистрации должно состоять от 3 до 16 латинских символов и может содержать цифры и подчеркивания
  - нельзя зарегистрировать пользователя с уже существующим именем
  - при несовпадении паролей в полях ввода "Pasword" регистрация не осуществляется
  - у пользователя есть возможность восстановить пароль
  - при авторизации и вводе неправильного адреса электронной почты или пароля пользователь должен получить сообщение об ошибке
  - пользователь при создании игры имеет возможность выбора соперника (против бота, друга или любого человека),уровня сложности игры (elementary, easy, medium, hard), лимита времени (от 3 до 60 минут), решаемой задачи
  - пользователь имеет возможность наблюдать за игрой других игроков в режиме реального времени
  - Каждый игрок видит код своего соперника в режиме он-лайн
  - пользователь имеет возможность просматривать завершенные игры в записи
  - задача в игровом режиме может отображаться на двух языках - русском и английском
  - в игре есть чат, в котором могут общаться зарегистрированные пользователи
  - пользователь имеет возможность создавать турниры
  - пользователь может участвовать в трунирах
  - игрок может проверить правильность своего решения
  - игрок может сдаться и завершить игру в любой момент
  - на главной странице отображаются вкладки LOBBY, TOURNAMENTS, COMPLETED GAMES
  - во вкладке LOBBY отображаются текущие игры
  - во вкладке TOURNAMENTS отображаются активные и завершенные турниры
  - во вкладке COMPLETED GAMES отображаются завершенные игры
  - в профиле пользователя отображается информация о его рейтинге, завершенных играх, активность в игре
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - пароль при регистрации должен содержать хотя бы одну заглавную букву, одину цифру и один спецсимвол
  - есть возможность выбора языка сайта между русским и английским
  - при завершении игры есть кнопка "поделиться достижением" в социальных сетях
  - при просмотре записи игры есть возможность сразу вернуться на вкладку COMPLETED GAMES
  - во вкладке LOBBY есть возможность отфильтровать игры по уровню сложности
  - у пользователя есть возможность добавить в друзья другого человека
  - при выборе уровня сложности игры и нажатии на любой уровень сложности не должно происходить смещение полей формы
